/* Explorar: las rutinas prediseñadas usan el mismo modelo que Mis rutinas. */
(function(){
const catalog=RTCatalog;
const state={view:'routines',category:'Todas',muscle:'Todos',search:'',difficulty:'Todas',location:'Todos',equipment:'Todos',type:'Todos'};
const muscles=['Todos','Pecho','Espalda','Hombros','Bíceps','Tríceps','Core','Cuádriceps','Isquiotibiales','Glúteos','Gemelos','Cuerpo completo'];
const folds=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const opts=(values,current)=>values.map(x=>`<option value="${rtEscape(x)}"${x===current?' selected':''}>${rtEscape(x)}</option>`).join('');
const allExercises=r=>r.days.flatMap(d=>d.exercises);
const entryFor=step=>catalog.getExercise(step.id);
const displayStep=step=>{const item=entryFor(step),alt=step.alternates.length?`<details class="rt-catalog-alt"><summary>Alternativas</summary>${step.alternates.map(name=>`<span>${rtEscape(name)}</span>`).join('')}</details>`:'';return `<li class="rt-catalog-exercise-row">${RTExerciseArt.svg(item?.name||'Ejercicio',item?.equipment||'','rt-art-small')}<div><strong>${rtEscape(item?.name||'Ejercicio')}</strong><small>${rtEscape(item?.primaryMuscle||'General')} · ${step.sets} × ${rtEscape(step.range)}${step.mode==='time'&&!/s/.test(step.range)?' s':''} · ${step.rest} s descanso</small></div>${alt}</li>`};
function payload(r,name=r.name){return RTCore.routine({name,settings:{days:r.days.map(d=>({name:d.name,exercises:d.exercises.map(x=>{const item=entryFor(x);return RTCore.exercise({name:item?.name||'Ejercicio',mode:x.mode,amount:x.amount,sets:x.sets,rest:x.rest,catalogId:x.id,primaryMuscle:item?.primaryMuscle||'',alternatives:x.alternates.map(a=>catalog.slug(a))})})})),order:r.category==='Deportes'?'circuit':'straight',prep:3,beep:3,sport:r.category==='Deportes'?r.name.replace(/^Rápida · /,''):'General'}})}
catalog.toRoutine=payload;
async function savePreset(r,edit=false){const names=savedRoutines.map(x=>x.name),name=edit||names.includes(r.name)?RTCore.duplicateName(r.name,names):r.name;const result=await rtSaveRoutine(payload(r,name));if(result.error){rtToast('No se pudo guardar la rutina.');return}rtClose();if(edit){showTab('mine');openRoutineEditor(result.data)}else rtToast('Agregada a Mis rutinas')}
function openPreset(r){const days=r.days.map((d,i)=>`<details class="rt-catalog-day"${i===0?' open':''}><summary>${rtEscape(d.name)} · ${d.exercises.length} ejercicios</summary><ul>${d.exercises.map(displayStep).join('')}</ul></details>`).join('');rtDialog(r.name,`<p class="rt-muted">${r.category==='Deportes'?'Complementaria · ':''}${rtEscape(r.description)} · ${rtEscape(r.level)} · ${rtEscape(r.duration)}</p><p class="rt-muted">${rtEscape(r.equipment)} · ${r.days.length} ${r.days.length===1?'día':'días'}</p>${days}<div id="rtPresetActions" class="rt-row"></div>`);$('#rtPresetActions').append(rtButton('Entrenar',()=>{rtClose();chooseRoutineDay(payload(r))},'primary'),rtButton('Agregar a mis rutinas',()=>savePreset(r)),rtButton('Personalizar',()=>savePreset(r,true)),rtButton('Compartir',()=>rtShare(payload(r)),'rt-small'))}
function routineMatches(r){const q=folds(state.search);return (state.category==='Todas'||r.category===state.category||state.category==='Favoritas'&&RT.favorites.routines.includes('catalog:'+r.id))&&(state.muscle==='Todos'||allExercises(r).some(x=>entryFor(x)?.primaryMuscle===state.muscle))&&(!q||folds(r.name+' '+r.description+' '+r.category+' '+r.days.map(d=>d.name).join(' ')).includes(q))}
function exerciseMatches(item,filters=state){const q=folds(filters.search);return (!q||folds(item.name+' '+item.primaryMuscle+' '+item.equipment).includes(q))&&(filters.muscle==='Todos'||item.primaryMuscle===filters.muscle)&&(filters.difficulty==='Todas'||item.difficulty===filters.difficulty)&&(filters.location==='Todos'||item.location===filters.location||item.location==='Ambos')&&(filters.equipment==='Todos'||item.equipment===filters.equipment)&&(filters.type==='Todos'||item.type===filters.type)}
function addExerciseToEditor(item){exercises.push(RTCore.exercise({name:item.name,mode:item.type==='Cardio'?'time':'reps',amount:item.type==='Cardio'?30:10,sets:2,rest:45,catalogId:item.id,primaryMuscle:item.primaryMuscle,alternatives:item.alternatives}));saveCurrentDay();renderExercises();buildPlan();rtClose();rtToast('Ejercicio agregado al día actual')}
function chooseDestination(item){if(!$('#routineEditor').classList.contains('hidden')&&!$('#mineSection').classList.contains('hidden'))return addExerciseToEditor(item);rtDialog('Agregar '+item.name,`<p class="rt-muted">Elegí una rutina y un día.</p><label>Rutina<select id="rtAddToRoutine">${opts(savedRoutines.map(r=>r.name),'')}</select></label><label>Día<select id="rtAddToDay"></select></label><div id="rtAddExerciseActions" class="rt-row"></div>`);const select=$('#rtAddToRoutine');select.replaceChildren();for(const r of savedRoutines){const o=document.createElement('option');o.value=r.id;o.textContent=r.name;select.append(o)}const updateDays=()=>{const r=savedRoutines.find(x=>x.id===select.value);$('#rtAddToDay').replaceChildren();if(!r)return;daysOf(r).forEach((d,i)=>{const o=document.createElement('option');o.value=i;o.textContent=d.name;$('#rtAddToDay').append(o)})};select.onchange=updateDays;updateDays();$('#rtAddExerciseActions').append(rtButton('Nueva rutina',()=>{rtClose();newRoutine();addExerciseToEditor(item)},'rt-small'));if(savedRoutines.length)$('#rtAddExerciseActions').append(rtButton('Agregar',async()=>{const r=savedRoutines.find(x=>x.id===select.value);if(!r)return;const copy=RTCore.routine(r);copy.settings.days[Number($('#rtAddToDay').value)].exercises.push(RTCore.exercise({name:item.name,mode:item.type==='Cardio'?'time':'reps',amount:item.type==='Cardio'?30:10,sets:2,rest:45,catalogId:item.id,primaryMuscle:item.primaryMuscle,alternatives:item.alternatives}));const result=await rtSaveRoutine(copy,r.id);if(result.error)return rtToast('No se pudo agregar el ejercicio.');rtClose();rtToast('Ejercicio agregado a '+r.name)},'primary'))}
function openExercise(item){rtDialog(item.name,`<div class="rt-art-detail">${RTExerciseArt.svg(item.name,item.equipment)}</div><p class="rt-muted">${rtEscape(item.primaryMuscle)} · ${rtEscape(item.difficulty)} · ${rtEscape(item.location)}</p><p class="rt-muted">Equipo: ${rtEscape(item.equipment)} · ${rtEscape(item.type)}</p>${item.alternatives.length?`<p class="rt-muted">Alternativas: ${item.alternatives.map(id=>rtEscape(catalog.getExercise(id)?.name||'')).join(', ')}</p>`:''}<div id="rtExerciseActions" class="rt-row"></div>`);$('#rtExerciseActions').append(rtButton('Agregar a rutina',()=>chooseDestination(item),'primary'),rtButton(RT.favorites.exercises.includes(item.name)?'★ Favorito':'☆ Favorito',()=>{rtFavorite('exercises',item.name);openExercise(item)},'rt-small'))}
function renderCatalog(){const root=$('#catalogSection');if(!root.querySelector('#rtCatalogList'))return;root.querySelector('#rtCatalogCategoryWrap').classList.toggle('hidden',state.view!=='routines');root.querySelector('.rt-catalog-search').classList.toggle('rt-exercise-search',state.view==='exercises');root.querySelector('#rtCatalogFilters').classList.toggle('hidden',state.view!=='exercises');root.querySelector('#rtCatalogViewRoutines').classList.toggle('primary',state.view==='routines');root.querySelector('#rtCatalogViewExercises').classList.toggle('primary',state.view==='exercises');const list=$('#rtCatalogList');list.replaceChildren();const items=state.view==='routines'?catalog.allRoutines.filter(routineMatches):catalog.exerciseLibrary.filter(item=>exerciseMatches(item));$('#rtCatalogCount').textContent=items.length+(state.view==='routines'?' rutinas':' ejercicios');for(const item of items){const card=document.createElement('article');card.className='rt-catalog-card'+(state.view==='exercises'?' rt-exercise-card':'');if(state.view==='exercises')card.insertAdjacentHTML('afterbegin',RTExerciseArt.svg(item.name,item.equipment));const heading=document.createElement('h3');heading.textContent=item.name;const summary=document.createElement('p');summary.className='rt-muted';summary.textContent=state.view==='routines'?item.description:item.primaryMuscle+' · '+item.difficulty+' · '+item.equipment;const meta=document.createElement('small');meta.className='rt-muted';if(state.view==='routines')meta.textContent=(item.category==='Deportes'?'Complementaria · ':'')+item.category+' · '+item.days.length+(item.days.length===1?' día':' días')+' · '+item.duration;const actions=document.createElement('div');actions.className='rt-row';if(state.view==='routines'){actions.append(rtButton('Ver rutina',()=>openPreset(item),'primary rt-small'),rtButton('+ Mis rutinas',()=>savePreset(item),'rt-small'),rtButton(RT.favorites.routines.includes('catalog:'+item.id)?'★':'☆',()=>{rtFavorite('routines','catalog:'+item.id);renderCatalog()},'rt-small'))}else actions.append(rtButton('Ver ejercicio',()=>openExercise(item),'primary rt-small'),rtButton('Agregar',()=>chooseDestination(item),'rt-small'));card.append(heading,summary,meta,actions);list.append(card)}if(!items.length)list.textContent='No hay resultados con esos filtros.'}
rtCatalog=function(){const section=$('#catalogSection');if(!section.querySelector('#rtCatalogList')){section.innerHTML=`<div class="card"><h2>Explorar</h2><div class="rt-row rt-catalog-tabs"><button id="rtCatalogViewRoutines" type="button" class="primary">Rutinas</button><button id="rtCatalogViewExercises" type="button">Ejercicios</button></div><div class="rt-catalog-search"><input id="rtCatalogSearch" type="search" placeholder="Buscar" aria-label="Buscar en Explorar"><label id="rtCatalogCategoryWrap">Lugar<select id="rtCatalogCategory">${opts(['Todas','Casa','Gimnasio','Deportes','Favoritas'],state.category)}</select></label><label>Músculo<select id="rtCatalogMuscle">${opts(muscles,state.muscle)}</select></label></div><details id="rtCatalogFilters" class="hidden"><summary>Más filtros</summary><div class="rt-grid rt-catalog-more"><label>Dificultad<select id="rtCatalogDifficulty">${opts(['Todas','Principiante','Intermedio','Avanzado'],state.difficulty)}</select></label><label>Ubicación<select id="rtCatalogLocation">${opts(['Todos','Casa','Gimnasio','Ambos'],state.location)}</select></label><label>Equipamiento<select id="rtCatalogEquipment">${opts(['Todos',...new Set(catalog.exerciseLibrary.map(x=>x.equipment))].sort(),state.equipment)}</select></label><label>Tipo<select id="rtCatalogType">${opts(['Todos','Fuerza','Core','Cardio','Potencia'],state.type)}</select></label></div></details><p id="rtCatalogCount" class="rt-muted"></p><div id="rtCatalogList" class="rt-catalog-list"></div></div>`;$('#rtCatalogSearch').value=state.search;$('#rtCatalogViewRoutines').onclick=()=>{state.view='routines';renderCatalog()};$('#rtCatalogViewExercises').onclick=()=>{state.view='exercises';renderCatalog()};for(const [id,key] of [['#rtCatalogCategory','category'],['#rtCatalogMuscle','muscle'],['#rtCatalogDifficulty','difficulty'],['#rtCatalogLocation','location'],['#rtCatalogEquipment','equipment'],['#rtCatalogType','type']])$(id).onchange=e=>{state[key]=e.target.value;renderCatalog()};$('#rtCatalogSearch').oninput=e=>{state.search=e.target.value;renderCatalog()}}renderCatalog()};
$('#form').insertAdjacentHTML('afterend','<button id="rtChooseLibraryExercise" type="button" class="rt-small">Elegir de la biblioteca</button>');
$('#rtChooseLibraryExercise').onclick=()=>{rtDialog('Biblioteca de ejercicios','<label>Buscar<input id="rtLibrarySearch" type="search" placeholder="Ejercicio"></label><label>Músculo<select id="rtLibraryMuscle"></select></label><div id="rtLibraryChoices" class="rt-catalog-picks"></div>');$('#rtLibraryMuscle').innerHTML=opts(muscles,'Todos');const draw=()=>{const filters={...state,search:$('#rtLibrarySearch').value,muscle:$('#rtLibraryMuscle').value,difficulty:'Todas',location:'Todos',equipment:'Todos',type:'Todos'};const box=$('#rtLibraryChoices');box.replaceChildren();for(const item of catalog.exerciseLibrary.filter(x=>exerciseMatches(x,filters))){const b=rtButton(item.name+' · '+item.primaryMuscle,()=>addExerciseToEditor(item),'rt-small');b.classList.add('rt-art-choice');b.insertAdjacentHTML('afterbegin',RTExerciseArt.svg(item.name,item.equipment,'rt-art-small'));box.append(b)}if(!box.childElementCount)box.textContent='Sin resultados.'};$('#rtLibrarySearch').oninput=draw;$('#rtLibraryMuscle').onchange=draw;draw()};
$('#rtChooseLibraryExercise').classList.add('rt-library-add');
$('#infoOverlay .infoSteps').innerHTML=[
 'En Mis rutinas creá o importá programas con varios días.',
 'En Explorar filtrá rutinas y ejercicios; guardá una copia para editarla.',
 'En Entrenar elegí el día y el orden, anotá cargas o cambiá un ejercicio.',
 'Usá Calendario para planificar y Cronómetro para marcar vueltas.',
 'Revisá Historial, Datos físicos y tus logros en Perfil.',
 'Elegí el color arriba y tocá ⇩ para instalar la app.',
 'Las rutinas funcionan sin conexión; historial y calendario quedan en este dispositivo.'
].map((line,i)=>'<div class="infoStep"><b>'+(i+1)+'</b><span>'+line+'</span></div>').join('');
$('#updatesOverlay .updateList').insertAdjacentHTML('afterbegin','<li>Explorá rutinas para casa, gimnasio y deportes; filtrá por músculo y guardá tus favoritas.</li>');

$('#replaceForm').insertAdjacentHTML('afterbegin','<div id="rtAlternativeChoices" class="rt-alternative-choices hidden"></div>');
$('#replaceForm .grid2:last-of-type').insertAdjacentHTML('beforebegin','<label id="rtRememberReplacement" class="rt-check hidden"><input id="rtSaveReplacement" type="checkbox">Guardar cambio en mi rutina</label>');
const previousOpenReplace=openReplace;
openReplace=function(){previousOpenReplace();const p=plan[idx],box=$('#rtAlternativeChoices');box.replaceChildren();const muscle=p?.primaryMuscle||catalog.getExercise(p?.catalogId)?.primaryMuscle;const alternatives=(p?.alternatives?.length?p.alternatives:catalog.getExercise(p?.catalogId)?.alternatives||[]).map(id=>catalog.getExercise(id)).filter(item=>item&&(!muscle||item.primaryMuscle===muscle));box.classList.toggle('hidden',!alternatives.length);if(alternatives.length){const heading=document.createElement('p');heading.className='rt-muted';heading.textContent='Alternativas para este ejercicio';box.append(heading);for(const item of alternatives){const b=rtButton(item.name+' · '+item.equipment,()=>{$('#replaceName').value=item.name;$('#replaceName').focus()},'rt-small rt-art-choice');b.insertAdjacentHTML('afterbegin',RTExerciseArt.svg(item.name,item.equipment,'rt-art-small'));box.append(b)}}$('#rtRememberReplacement').classList.toggle('hidden',!savedRoutines.some(r=>r.id===RT.sessionRoutine));$('#rtSaveReplacement').checked=false};
const originalReplaceSubmit=$('#replaceForm').onsubmit;
$('#replaceForm').onsubmit=async e=>{const current=plan[idx],routine=savedRoutines.find(r=>r.id===RT.sessionRoutine),save=$('#rtSaveReplacement').checked&&!$('#rtRememberReplacement').classList.contains('hidden'),name=$('#replaceName').value.trim(),sets=Number($('#replaceSets').value),reps=Number($('#replaceReps').value);originalReplaceSubmit(e);if(!save||!routine||!$('#replaceOverlay').classList.contains('hidden')||!current||current.exerciseId==null)return;const copy=RTCore.routine(routine),day=copy.settings.days[RT.sessionDay];if(!day?.exercises[current.exerciseId])return;const item=catalog.getExercise(catalog.slug(name));day.exercises[current.exerciseId]=RTCore.exercise({name,mode:'reps',amount:reps,sets,rest:current.rest,catalogId:item?.id||'',primaryMuscle:item?.primaryMuscle||current.primaryMuscle,alternatives:item?.alternatives||[]});copy.exercises=copy.settings.days[0].exercises;const result=await rtSaveRoutine(copy,routine.id);rtToast(result.error?'El cambio quedó solo en esta sesión.':'Cambio guardado en tu rutina')};
// Dibujos también en el editor y en el paso actual del entrenamiento.
const renderExercisesWithoutArt=renderExercises;
renderExercises=function(){renderExercisesWithoutArt();$$('#list .exercise').forEach((row,i)=>{const x=exercises[i],item=catalog.getExercise(x?.catalogId||catalog.slug(x?.name||''));if(x)row.insertAdjacentHTML('afterbegin',RTExerciseArt.svg(x.name,item?.equipment||'','rt-art-small'))})};
$('#exercise').insertAdjacentHTML('afterend','<div id="rtCurrentExerciseArt" class="rt-art-current hidden"></div>');
const renderCurrentStepWithoutArt=renderCurrentStep;
renderCurrentStep=function(auto=false){renderCurrentStepWithoutArt(auto);const p=plan[idx],holder=$('#rtCurrentExerciseArt');holder.classList.toggle('hidden',p?.type!=='work');if(p?.type==='work'){const item=catalog.getExercise(p.catalogId||catalog.slug(p.name));holder.innerHTML=RTExerciseArt.svg(p.name,item?.equipment||'')}};
const idleWithoutArt=idle;
idle=function(){idleWithoutArt();$('#rtCurrentExerciseArt').classList.add('hidden')};
const loadStepWithoutArt=loadStep;
loadStep=function(i){loadStepWithoutArt(i);if(idx>=plan.length)$('#rtCurrentExerciseArt').classList.add('hidden')};
const showCustomPickerWithoutArt=rtShowCustomPicker;
rtShowCustomPicker=function(){showCustomPickerWithoutArt();if($('#customOrderOverlay').classList.contains('hidden'))return;for(const button of $$('#customOrderList button')){const name=button.firstChild?.textContent||'',item=catalog.getExercise(catalog.slug(name));button.insertAdjacentHTML('beforeend',RTExerciseArt.svg(name,item?.equipment||'','rt-art-small'))}};
})();
