/* Routine Timer v26 — profile, planning and training tools. */
const RT={profile:{},prefs:{},schedule:{},favorites:{routines:[],exercises:[]},order:[],active:null,watch:{elapsed:0,start:null,laps:[]},week:0,authUser:null,syncing:false,sessionRoutine:null,sessionDay:0};
const SPORTS=['Musculación / Bodybuilding','CrossFit','Hyrox','Fútbol','Básquet','Ciclismo','Running','Natación','Tenis','Pádel','Vóley','Rugby','Hockey','Handball','Boxeo','Artes marciales','Calistenia','Gimnasia','Atletismo','Triatlón','Yoga','Pilates','Caminata','Otro deporte'];
const rtKey=k=>'rt26:'+currentUser.id+':'+k;
function rtRead(k,f){try{return JSON.parse(localStorage.getItem(rtKey(k)))??f}catch{return f}}
function rtWrite(k,v){if(currentUser)localStorage.setItem(rtKey(k),JSON.stringify(v))}
function rtEscape(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function rtButton(text,fn,cls=''){const b=document.createElement('button');b.type='button';b.textContent=text;b.className=cls;b.onclick=fn;return b}
function rtToast(text,gold=false){let el=$('#rtToast');if(!el){el=document.createElement('div');el.id='rtToast';el.role='status';document.body.append(el)}el.className='rt-toast'+(gold?' rt-gold rt-celebrate':'');el.textContent=text;clearTimeout(RT.toastTimer);RT.toastTimer=setTimeout(()=>el.remove(),6500)}
function rtDialog(title,html){$('#rtDialogTitle').textContent=title;$('#rtDialogBody').innerHTML=html;$('#rtDialogOverlay').classList.remove('hidden');$('#rtCloseDialog').focus()}
function rtClose(){$('#rtDialogOverlay').classList.add('hidden')}
function rtSection(id,label){const b=rtButton(label,()=>showTab(id));b.id='tab'+id;$('#appTabs').append(b);const s=document.createElement('section');s.id=id+'Section';s.className='rt-section hidden';$('#trainSection').after(s);return s}
document.body.insertAdjacentHTML('beforeend','<div id="rtDialogOverlay" class="infoOverlay hidden" role="dialog" aria-modal="true" aria-labelledby="rtDialogTitle"><div class="infoPanel rt-dialog"><div class="rt-row" style="justify-content:space-between"><h2 id="rtDialogTitle"></h2><button id="rtCloseDialog" aria-label="Cerrar">×</button></div><div id="rtDialogBody"></div></div></div>');
$('#rtCloseDialog').onclick=rtClose;$('#rtDialogOverlay').onclick=e=>{if(e.target.id==='rtDialogOverlay')rtClose()};document.addEventListener('keydown',e=>{if(e.key==='Escape')rtClose()});
rtSection('home','Inicio');$('#appTabs').prepend($('#tabhome'));
rtSection('calendar','Calendario');rtSection('watch','Cronómetro');rtSection('achievements','Logros');rtSection('catalog','Explorar');rtSection('admin','Administración');$('#tabadmin').classList.add('hidden');$('#tabCreate').classList.add('hidden');$('#tabachievements').classList.add('hidden');
const rtEditor=document.createElement('div');rtEditor.id='routineEditor';rtEditor.className='hidden';$('#mineSection').append(rtEditor);['wizard1','wizard2','wizard3'].forEach(id=>rtEditor.append($('#'+id)));
function rtOpenEditor(){rtEditor.classList.remove('hidden');rtEditor.scrollIntoView({behavior:'smooth',block:'start'})}
function rtCloseEditor(){rtEditor.classList.add('hidden')}
$('#routinesList').insertAdjacentHTML('beforebegin','<h3 id="rtMineHeading">Mis rutinas</h3>');
const oldShowTab=showTab;
showTab=function(name){if(!currentUser&&name!=='create')return;if(currentUser&&name==='create')name='mine';if(name!=='watch'&&RT.watchFull)rtWatchFullscreen(false);if(name==='mine')rtCloseEditor();for(const key of ['home','calendar','watch','achievements','catalog','admin']){$('#'+key+'Section').classList.add('hidden');$('#tab'+key).classList.remove('primary')}if(['home','calendar','watch','achievements','catalog','admin'].includes(name)){oldShowTab('none');$('#'+name+'Section').classList.remove('hidden');$('#tab'+name).classList.add('primary');({home:rtHome,calendar:rtCalendar,watch:rtWatchView,achievements:rtAchievements,catalog:rtCatalog,admin:rtAdmin})[name]()}else oldShowTab(name)};
$('#accountChip').outerHTML='<button id="accountChip" class="rt-account" type="button" aria-label="Mi perfil" title="Mi perfil"></button>';$('#accountChip').onclick=()=>rtProfile(false);$('#logoutBtn').classList.add('hidden');
function rtPaintAccount(){const b=$('#accountChip');b.setAttribute('aria-label','Mi perfil');b.title='Mi perfil';b.innerHTML='<svg viewBox="0 0 24 24" width="19" height="19" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="8" r="3.5"/><path d="M5 20v-2c0-3 2.5-5 7-5s7 2 7 5v2"/></svg>'}
const oldAuthView=authView;
authView=function(){const changed=RT.authUser!==currentUser?.id;RT.authUser=currentUser?.id||null;if(changed){stop(false);plan=[];idx=-1;setLogs={};exercises=[];workoutStartedAt=null;workoutRecorded=false;savedRoutines=[];RT.favorites={routines:[],exercises:[]};RT.order=[];RT.active=null;RT.profile={};RT.prefs={};RT.schedule={};}if(currentUser){RT.profile=rtRead('profile',currentUser.user_metadata?.training_profile||{});RT.prefs=rtRead('prefs',{mass:'kg',height:'cm',voice:false,season:'auto'});RT.schedule=rtRead('schedule',{});RT.favorites=rtRead('favorites',{routines:[],exercises:[]});RT.order=rtRead('order',[]);RT.active=rtRead('active',null);RT.watch=rtRead('watch',{elapsed:0,start:null,laps:[]});rtSeason()}oldAuthView();rtPaintAccount();$('#logoutBtn').classList.add('hidden');$('#tabadmin').classList.toggle('hidden',!currentUser||!(currentUser.app_metadata?.role==='admin'||currentUser.email?.toLowerCase()==='justimanzano@gmail.com'));if(currentUser&&changed){if(idx<0)showTab('home');if(!RT.profile.completed)setTimeout(()=>rtProfile(true),250);rtSharedIncoming()}if(!currentUser){rtClose();RT.watch={elapsed:0,start:null,laps:[]};RT.sessionRoutine=null;RT.sessionDay=0}rtConnection()};
function rtProfileFields(p,prefix='pf'){const field=(id,label,type,value,extra='')=>`<label>${label}<input id="${prefix+id}" type="${type}" value="${rtEscape(value??'')}" ${extra}></label>`;return `<div class="grid2"><label>Deporte principal<select id="${prefix}sport">${SPORTS.map(s=>`<option ${p.sport===s?'selected':''}>${s}</option>`).join('')}</select></label>${field('other','Otro deporte (si corresponde)','text',p.other,'maxlength="60"')}</div><div class="grid2">${field('frequency','Días de entrenamiento por semana','number',p.frequency??3,'min="1" max="7" required')}${field('months','Hace cuánto entrenás (meses)','number',p.months??0,'min="0" max="1200" required')}</div>${field('minutes','Duración habitual de una sesión (min)','number',p.minutes??60,'min="1" max="600" required')}<label>Género<select id="${prefix}sex"><option value="">Prefiero no indicarlo</option>${['masculino','femenino','otro'].map(s=>`<option value="${s}" ${p.sex===s?'selected':''}>${s}</option>`).join('')}</select></label><fieldset class="rt-fieldset"><legend>Datos físicos opcionales</legend><p class="rt-muted">Podés dejarlos vacíos. Se usan como registro personal.</p><div class="grid2">${field('age','Edad','number',p.age,'min="1" max="120"')}${field('height','Estatura (cm)','number',p.height,'min="50" max="260" step="0.1"')}</div>${field('weight','Peso (kg)','number',p.weight,'min="15" max="400" step="0.1"')}</fieldset>`}
function rtReadProfile(prefix='pf'){const v=id=>$('#'+prefix+id).value;const p={completed:true,sport:v('sport'),other:v('other').trim(),frequency:Number(v('frequency')),months:Number(v('months')),minutes:Number(v('minutes')),sex:v('sex'),age:v('age')===''?null:Number(v('age')),height:v('height')===''?null:Number(v('height')),weight:v('weight')===''?null:Number(v('weight'))};if(p.sport==='Otro deporte'&&!p.other)throw Error('Escribí el nombre del deporte.');if(p.frequency<1||p.frequency>7||!Number.isInteger(p.frequency)||p.months<0||p.months>1200||p.minutes<1||p.minutes>600)throw Error('Revisá los datos de entrenamiento.');return p}
function rtProfile(onboarding){rtDialog(onboarding?'Contanos cómo entrenás':'Mi perfil y preferencias',`<p class="rt-muted">${rtEscape(currentUser.email||'Cuenta guardada')} · ${navigator.onLine?'Con conexión':'Sin conexión'}</p><form id="rtProfileForm">${rtProfileFields({...RT.profile,sex:RT.profile.sex??currentUser.user_metadata?.sex})}<p class="rt-muted">Nivel orientativo: Principiante; Avanzado desde 12 meses y 2 días/semana; Pro desde 36 meses y 4 días/semana. No es una evaluación de capacidad ni una razón para entrenar más.</p><div class="grid2"><label>Cargas<select id="pfmass"><option value="kg">kg</option><option value="lbs">lbs</option></select></label><label>Estatura<select id="pfunit"><option value="cm">cm</option><option value="m">m</option><option value="in">pulgadas</option></select></label></div><label class="rt-check"><input id="pfvoice" type="checkbox">Avisos de voz</label><label>Diseño de temporada<select id="pfseason"><option value="auto">Automático</option><option value="none">Sin decoración</option><option value="christmas">Navidad</option><option value="newyear">Año nuevo</option><option value="kings">Reyes</option></select></label><p class="rt-muted">El perfil se guarda en tu cuenta de Supabase. Las preferencias, planificación, historial y favoritos se guardan en este dispositivo.</p><button class="primary" type="submit">Aplicar configuración</button><p id="pfmsg" role="status"></p></form><details id="rtProfileAchievements" class="rt-fieldset"><summary>Mis logros</summary><div id="rtProfileAchievementsContent"></div></details><button id="pfLogout" class="rt-small">Cerrar sesión</button>`);rtAchievements();$('#rtProfileAchievementsContent').innerHTML=$('#achievementsSection').innerHTML;$('#pfmass').value=RT.prefs.mass||'kg';$('#pfunit').value=RT.prefs.height||'cm';$('#pfvoice').checked=!!RT.prefs.voice;$('#pfseason').value=RT.prefs.season||'auto';$('#pfLogout').onclick=async()=>{rtClose();localStorage.removeItem('rtOfflineUser');await db.auth.signOut();currentUser=null;authView()};$('#rtProfileForm').onsubmit=async e=>{e.preventDefault();try{const p=rtReadProfile();RT.profile=p;RT.prefs={mass:$('#pfmass').value,height:$('#pfunit').value,voice:$('#pfvoice').checked,season:$('#pfseason').value};rtWrite('profile',p);if(p.age&&p.height&&p.weight){const records=physicalRecords.filter(r=>r.date!==localDate());records.push({date:localDate(),age:p.age,height:p.height,weight:p.weight});localStorage.setItem(physicalKey(),JSON.stringify(records));loadPhysicalRecords()}rtWrite('profilePending',true);rtWrite('prefs',RT.prefs);rtSeason();rtUnitLabels();renderPhysical();renderWorkoutHistory();if(idx>=0&&idx<plan.length)renderCurrentStep(false);const ok=await rtSyncProfile();rtClose();rtPaintAccount();rtHome();rtToast(ok?'Perfil actualizado':'Guardado en este dispositivo. Pendiente de sincronización.')}catch(err){$('#pfmsg').textContent=err.message}}}
const oldSign=sign;
sign=async function(mode){if(mode!=='signup')return oldSign(mode);if(!$('#signupDetails')){$('#loggedOut').insertAdjacentHTML('beforeend',`<form id="signupDetails">${rtProfileFields({},'su')}<p class="rt-muted">Guardaremos este perfil junto con tu cuenta para personalizar la app. Los datos físicos son opcionales.</p><button class="primary" type="submit">Crear mi cuenta</button></form>`);$('#accountCard').classList.add('rt-signup');$('#accountCard h2').textContent='Crear cuenta';$('#signupDetails').onsubmit=e=>{e.preventDefault();sign('signup')};$('#susport').focus();return}if(!$('#signupDetails').reportValidity())return;try{const p=rtReadProfile('su'),email=$('#authEmail').value.trim(),password=$('#authPassword').value;if(!email||password.length<6)throw Error('Ingresá un email y una contraseña de al menos 6 caracteres.');$('#signupBtn').disabled=true;const {error,data}=await db.auth.signUp({email,password,options:{data:{sex:p.sex,training_profile:p}}});if(error)throw error;message($('#authMsg'),data.session?'Cuenta creada':'Revisá tu email para confirmar la cuenta.')}catch(e){message($('#authMsg'),e.message,true)}finally{$('#signupBtn').disabled=false}};
async function rtSyncProfile(){if(!currentUser||!navigator.onLine||!rtRead('profilePending',false))return !rtRead('profilePending',false);try{const uid=currentUser.id,payload=JSON.stringify(RT.profile);const {error}=await db.auth.updateUser({data:{training_profile:RT.profile,sex:RT.profile.sex}});if(error||currentUser?.id!==uid)return false;if(payload===JSON.stringify(RT.profile))rtWrite('profilePending',false);return true}catch{return false}}
function rtSeason(){let season=RT.prefs.season||'auto';if(season==='auto'){const d=new Date(),m=d.getMonth()+1,n=d.getDate();season=m===12&&n<=26?'christmas':m===12&&n>=27||m===1&&n<=2?'newyear':m===1&&n<=6?'kings':'none'}document.documentElement.dataset.season=season}
function rtMass(kg){return Number(kg)*(RT.prefs.mass==='lbs'?2.2046226218:1)}function rtKg(v){return Number(v)/(RT.prefs.mass==='lbs'?2.2046226218:1)}function rtMassText(kg){return rtMass(kg).toLocaleString('es-AR',{maximumFractionDigits:1})+' '+(RT.prefs.mass||'kg')}
function rtHeight(cm){return Number(cm)/(RT.prefs.height==='m'?100:RT.prefs.height==='in'?2.54:1)}
function rtUnitLabels(){const input=$('#exerciseLoad');input.max=rtMass(1000);$('#physicalHeight').step=RT.prefs.height==='m'?'0.01':'0.1';$('#historySection .historyChart h3').textContent='Volumen levantado por sesión ('+(RT.prefs.mass||'kg')+')';input.parentNode.childNodes[0].nodeValue='Carga utilizada ('+(RT.prefs.mass||'kg')+')';$('#physicalWeight').parentNode.childNodes[0].nodeValue='Peso ('+(RT.prefs.mass||'kg')+')';$('#physicalHeight').parentNode.childNodes[0].nodeValue='Altura ('+(RT.prefs.height||'cm')+')';$('#physicalWeight').min=rtMass(15);$('#physicalWeight').max=rtMass(400);$('#physicalHeight').min=rtHeight(50);$('#physicalHeight').max=rtHeight(260)}
function rtConnection(){let el=$('#rtConnection');if(!el){el=document.createElement('p');el.id='rtConnection';el.className='rt-offline';$('.header').after(el)}el.textContent=currentUser?(!navigator.onLine?'Sin conexión · rutinas guardadas disponibles':rtRead('queue',[]).length?'Cambios pendientes de sincronización':''):''}
/* Offline mutations are scoped to the signed-in user and replayed with RLS. */
async function rtSaveRoutine(payload,id=null){if(!currentUser)return {error:{message:'Iniciá sesión'}};const clean=RTCore.routine(payload),row={...clean,user_id:currentUser.id,id:id||crypto.randomUUID(),updated_at:new Date().toISOString()};const rows=rtRead('routines',savedRoutines).filter(x=>x.id!==row.id);rows.unshift(row);rtWrite('routines',rows);const queue=rtRead('queue',[]).filter(x=>x.id!==row.id);queue.push({id:row.id,type:'save',row});rtWrite('queue',queue);savedRoutines=rows;await rtSyncRoutines();renderRoutines();rtToast(rtRead('queue',[]).some(x=>x.id===row.id)?'Rutina guardada aquí · pendiente de sincronización':'Rutina guardada y sincronizada');return {data:row,error:null}}
async function rtDeleteRoutine(id){const rows=rtRead('routines',savedRoutines).filter(r=>r.id!==id);rtWrite('routines',rows);rtWrite('queue',[...rtRead('queue',[]).filter(x=>x.id!==id),{id,type:'delete'}]);savedRoutines=rows;await rtSyncRoutines();renderRoutines()}
async function rtSyncRoutines(){if(!currentUser||!navigator.onLine||RT.syncing)return;RT.syncing=true;const uid=currentUser.id;try{for(const op of rtRead('queue',[])){if(currentUser?.id!==uid)break;let result;try{result=op.type==='delete'?await db.from('routines').delete().eq('id',op.id).eq('user_id',uid):await db.from('routines').upsert(op.row,{onConflict:'id'})}catch{break}if(currentUser?.id!==uid)break;if(result.error){rtToast('Cambios guardados aquí; no se pudo sincronizar.');break}rtWrite('queue',rtRead('queue',[]).filter(x=>!(x.id===op.id&&JSON.stringify(x)===JSON.stringify(op))))}}finally{RT.syncing=false;rtConnection()}}
loadRoutines=async function(){if(!currentUser){savedRoutines=[];renderRoutines();return}const uid=currentUser.id;savedRoutines=rtRead('routines',[]);renderRoutines();if(!navigator.onLine)return;await rtSyncRoutines();try{const {data,error}=await db.from('routines').select('id,name,exercises,settings,updated_at').eq('user_id',uid).order('updated_at',{ascending:false});if(currentUser?.id!==uid)return;if(error)throw error;const pending=rtRead('queue',[]),ids=new Set(pending.map(x=>x.id));savedRoutines=[...pending.filter(x=>x.type==='save').map(x=>x.row),...(data||[]).filter(x=>!ids.has(x.id))];rtWrite('routines',savedRoutines);renderRoutines();if(!$('#homeSection').classList.contains('hidden'))rtHome();message($('#mineMsg'),'')}catch{message($('#mineMsg'),'Mostrando rutinas guardadas en este dispositivo.')}};
window.addEventListener('online',async()=>{rtConnection();await rtSyncProfile();await loadRoutines()});window.addEventListener('offline',rtConnection);
/* Routine cards, sharing and ordering. */
$('#routinesList').insertAdjacentHTML('beforebegin','<div class="rt-row" style="margin:14px 0"><input id="rtSearch" placeholder="Buscar rutina" aria-label="Buscar rutina"><select id="rtFilter" aria-label="Filtrar rutinas"><option value="all">Todas</option><option value="favorites">Favoritas</option><option value="active">Activa</option><option value="multi">Varios días</option></select><button id="rtImportCode">Importar código o link</button></div>');$('#rtSearch').oninput=()=>renderRoutines();$('#rtFilter').onchange=()=>renderRoutines();$('#rtImportCode').onclick=()=>rtImportDialog();
renderRoutines=function(){const box=$('#routinesList');box.innerHTML='';const q=$('#rtSearch').value.toLowerCase(),filter=$('#rtFilter').value;const rows=[...savedRoutines].sort((a,b)=>(RT.order.indexOf(a.id)<0?999:RT.order.indexOf(a.id))-(RT.order.indexOf(b.id)<0?999:RT.order.indexOf(b.id))).filter(r=>r.name.toLowerCase().includes(q)&&(filter!=='favorites'||RT.favorites.routines.includes(r.id))&&(filter!=='active'||RT.active===r.id)&&(filter!=='multi'||daysOf(r).length>1));for(const r of rows){const c=document.createElement('article');c.className='routineCard rt-drag';c.draggable=true;c.dataset.id=r.id;const heading=rtButton(r.name,()=>openRoutineEditor(r));heading.style.fontWeight='700';c.append(heading);const meta=document.createElement('p');meta.className='rt-muted';meta.textContent=daysOf(r).length+' días · '+totalExerciseCount(r)+' ejercicios · ≈ '+durationLabel(totalRoutineTime(r))+(r.id===RT.active?' · ACTIVA':'');c.append(meta);const actions=document.createElement('div');actions.className='rt-row';actions.append(rtButton('Entrenar',()=>chooseRoutineDay(r),'primary'),rtButton(RT.favorites.routines.includes(r.id)?'★':'☆',()=>{rtFavorite('routines',r.id);renderRoutines()},'rt-small'),rtButton('Opciones',()=>rtRoutineOptions(r),'rt-small'));c.append(actions);c.ondragstart=e=>e.dataTransfer.setData('text/plain','routine:'+r.id);c.ondragover=e=>e.preventDefault();c.ondrop=e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain').replace(/^routine:/,'');const ids=[...savedRoutines].sort((a,b)=>(RT.order.indexOf(a.id)<0?999:RT.order.indexOf(a.id))-(RT.order.indexOf(b.id)<0?999:RT.order.indexOf(b.id))).map(x=>x.id);if(!ids.includes(id)||id===r.id)return;ids.splice(ids.indexOf(id),1);ids.splice(ids.indexOf(r.id),0,id);RT.order=ids;rtWrite('order',ids);renderRoutines()};box.append(c)}if(!rows.length)box.textContent='No hay rutinas que coincidan.'};
function rtFavorite(kind,id){RT.favorites[kind]=RT.favorites[kind].includes(id)?RT.favorites[kind].filter(x=>x!==id):[...RT.favorites[kind],id];rtWrite('favorites',RT.favorites)}
function rtRoutineOptions(r){rtDialog(r.name,'<div id="rtRoutineActions" class="rt-row"></div>');$('#rtRoutineActions').append(rtButton('Editar',()=>{rtClose();openRoutineEditor(r)}),rtButton('Usar como rutina activa',()=>{RT.active=r.id;rtWrite('active',r.id);rtClose();renderRoutines();showTab('calendar')}),rtButton('Duplicar',async()=>{const copy=RTCore.routine(r);copy.name=RTCore.duplicateName(r.name,savedRoutines.map(x=>x.name));await rtSaveRoutine(copy);rtClose();rtToast('Rutina duplicada')}),rtButton('Compartir',()=>rtShare(r)),rtButton('Planificar',()=>rtPlanDialog(r)),rtButton('Mover al principio',()=>{RT.order=[r.id,...RT.order.filter(id=>id!==r.id)];rtWrite('order',RT.order);rtClose();renderRoutines()}),rtButton('Eliminar',async()=>{if(confirm('¿Eliminar esta rutina?')){await rtDeleteRoutine(r.id);rtClose()}}))}
function rtEncode(r){const json=JSON.stringify({version:1,routine:RTCore.routine(r)});return 'RT1.'+btoa(Array.from(new TextEncoder().encode(json),b=>String.fromCharCode(b)).join('')).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'')}
function rtDecode(text){let raw=text.trim();if(raw.includes('#routine='))raw=raw.split('#routine=')[1].split('&')[0];if(raw.length>180000||!raw.startsWith('RT1.'))throw Error('Código de rutina inválido.');const bytes=Uint8Array.from(atob(raw.slice(4).replaceAll('-','+').replaceAll('_','/')),c=>c.charCodeAt(0)),obj=JSON.parse(new TextDecoder().decode(bytes));if(obj.version!==1)throw Error('Versión de código no compatible');return RTCore.routine(obj.routine)}
function rtShare(r){const code=rtEncode(r),link=location.origin+location.pathname+'#routine='+code;rtDialog('Compartir rutina',`<p>El código incluye únicamente la rutina y sus ejercicios. Quien lo reciba puede importarla.</p><label>Link<textarea id="rtShareLink" readonly></textarea></label><label>Código<textarea id="rtShareCode" readonly></textarea></label><button id="rtCopyShare">Copiar link</button><p class="rt-muted">Las rutinas grandes generan enlaces largos; podés copiar el código completo.</p>`);$('#rtShareLink').value=link;$('#rtShareCode').value=code;$('#rtCopyShare').onclick=async()=>{try{await navigator.clipboard.writeText(link);rtToast('Link copiado')}catch{$('#rtShareLink').select();rtToast('Seleccioná y copiá el link')}}}
function rtImportDialog(initial=''){rtDialog('Importar rutina compartida','<label>Código o link<textarea id="rtCodeInput"></textarea></label><button id="rtCheckCode">Ver rutina</button><div id="rtCodePreview"></div>');$('#rtCodeInput').value=initial;$('#rtCheckCode').onclick=()=>{try{const r=rtDecode($('#rtCodeInput').value);$('#rtCodePreview').textContent=r.name+' · '+r.settings.days.length+' días · '+r.settings.days.reduce((n,d)=>n+d.exercises.length,0)+' ejercicios';$('#rtCodePreview').append(rtButton('Importar a mis rutinas',async()=>{await rtSaveRoutine(r);history.replaceState(null,'',location.pathname+location.search);rtClose();showTab('mine');rtToast('Rutina importada')}))}catch(e){$('#rtCodePreview').textContent=e.message}}}
function rtSharedIncoming(){if(location.hash.startsWith('#routine='))rtImportDialog(location.href)}
/* Planning dates use local calendar dates, never UTC dates. */
function rtDate(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function rtMonday(){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-(d.getDay()+6)%7+RT.week*7);return d}
function rtPlanDialog(r=null,date=localDate()){rtDialog('Planificar entrenamiento',`<form id="rtPlanForm"><label>Rutina<select id="rtPlanRoutine">${savedRoutines.map(x=>`<option value="${rtEscape(x.id)}">${rtEscape(x.name)}</option>`).join('')}</select></label><label>Día de la rutina<select id="rtPlanDay"></select></label><label>Fecha<input type="date" id="rtPlanDate" value="${date}" required></label><label>Repetir semanalmente<select id="rtPlanWeeks"><option value="1">Solo esta fecha</option><option value="4">4 semanas</option><option value="8">8 semanas</option><option value="12">12 semanas</option></select></label><button class="primary">Guardar planificación</button></form>`);if(!savedRoutines.length){$('#rtPlanForm').textContent='Primero creá una rutina.';return}if(r)$('#rtPlanRoutine').value=r.id;const days=()=>{$('#rtPlanDay').innerHTML=daysOf(savedRoutines.find(x=>x.id===$('#rtPlanRoutine').value)).map((d,i)=>`<option value="${i}">${rtEscape(d.name)}</option>`).join('')};$('#rtPlanRoutine').onchange=days;days();$('#rtPlanForm').onsubmit=e=>{e.preventDefault();const routineId=$('#rtPlanRoutine').value,dayIndex=Number($('#rtPlanDay').value),start=new Date($('#rtPlanDate').value+'T12:00:00');for(let i=0;i<Number($('#rtPlanWeeks').value);i++){const d=new Date(start);d.setDate(d.getDate()+7*i);const key=rtDate(d);RT.schedule[key]??=[];if(!RT.schedule[key].some(x=>x.routineId===routineId&&x.dayIndex===dayIndex))RT.schedule[key].push({id:crypto.randomUUID(),routineId,dayIndex})}rtWrite('schedule',RT.schedule);rtClose();showTab('calendar')}}
function rtMoveEvent(from,id,to){if(!/^\d{4}-\d{2}-\d{2}$/.test(to)||from===to)return;const event=RT.schedule[from]?.find(x=>x.id===id);if(!event)return;RT.schedule[from]=RT.schedule[from].filter(x=>x.id!==id);(RT.schedule[to]??=[]).push(event);rtWrite('schedule',RT.schedule);rtCalendar()}
function rtCalendar(){const s=$('#calendarSection'),start=rtMonday(),end=new Date(start);end.setDate(end.getDate()+6);s.innerHTML='<div class="card"><div class="rt-calendar-header"><h2>Calendario</h2><div class="rt-row"><button id="rtWeekPrev" class="rt-small" aria-label="Semana anterior">←</button><strong id="rtWeekLabel"></strong><button id="rtWeekNext" class="rt-small" aria-label="Semana siguiente">→</button><button id="rtPlanNew" class="primary rt-small">+ Planificar</button></div></div><p class="rt-muted">Tocá un día para planificar. Tocá un entrenamiento para moverlo o eliminarlo; también podés arrastrarlo.</p><div id="rtCalendarGrid" class="rt-calendar"></div></div>';$('#rtWeekLabel').textContent=start.toLocaleDateString('es-AR',{day:'numeric',month:'short'})+' – '+end.toLocaleDateString('es-AR',{day:'numeric',month:'short'});$('#rtWeekPrev').onclick=()=>{RT.week--;rtCalendar()};$('#rtWeekNext').onclick=()=>{RT.week++;rtCalendar()};$('#rtPlanNew').onclick=()=>rtPlanDialog(savedRoutines.find(r=>r.id===RT.active));for(let n=0;n<7;n++){const d=new Date(start);d.setDate(d.getDate()+n);const date=rtDate(d),cell=document.createElement('div');cell.className='rt-day'+(date===localDate()?' today':'');cell.setAttribute('role','button');cell.tabIndex=0;cell.setAttribute('aria-label','Planificar el '+d.toLocaleDateString('es-AR',{weekday:'long',day:'numeric',month:'long'}));const title=document.createElement('strong');title.textContent=d.toLocaleDateString('es-AR',{weekday:'short',day:'numeric',month:'short'});cell.append(title);cell.onclick=e=>{if(e.target===cell||e.target===title)rtPlanDialog(null,date)};cell.onkeydown=e=>{if(e.target===cell&&(e.key==='Enter'||e.key===' ')){e.preventDefault();rtPlanDialog(null,date)}};for(const event of RT.schedule[date]||[]){const r=savedRoutines.find(x=>x.id===event.routineId),el=document.createElement('div');el.className='rt-event';el.draggable=true;el.setAttribute('role','button');el.tabIndex=0;const done=workoutHistory.some(h=>h.localDay===date&&h.routineId===event.routineId&&h.dayIndex===event.dayIndex);el.textContent=r?(done?'✓ ':'')+r.name+' · '+(daysOf(r)[event.dayIndex]?.name||'Día eliminado'):'Rutina no disponible';el.onclick=e=>{e.stopPropagation();rtCalendarEvent(date,event,r)};el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();rtCalendarEvent(date,event,r)}};el.ondragstart=e=>{e.stopPropagation();e.dataTransfer.setData('text/plain',JSON.stringify({date,id:event.id}))};cell.append(el)}cell.ondragover=e=>e.preventDefault();cell.ondrop=e=>{e.preventDefault();try{const p=JSON.parse(e.dataTransfer.getData('text/plain'));rtMoveEvent(p.date,p.id,date)}catch{}};$('#rtCalendarGrid').append(cell)}}
function rtCalendarEvent(date,event,r){rtDialog(r?.name||'Entrenamiento',`<p>${rtEscape(new Date(date+'T12:00:00').toLocaleDateString('es-AR',{dateStyle:'full'}))}</p><div id="rtEventActions" class="rt-row"></div>`);const actions=$('#rtEventActions');if(r&&daysOf(r)[event.dayIndex])actions.append(rtButton('Entrenar',()=>{rtClose();openRoutine(r,event.dayIndex);showTab('train')},'primary'));actions.append(rtButton('Mover',()=>{rtDialog('Mover entrenamiento',`<label>Nueva fecha<input id="rtMoveDate" type="date" value="${date}"></label><button id="rtMoveConfirm" class="primary">Mover</button>`);$('#rtMoveConfirm').onclick=()=>{rtMoveEvent(date,event.id,$('#rtMoveDate').value);rtClose()}},'rt-small'),rtButton('Eliminar',()=>{RT.schedule[date]=RT.schedule[date].filter(x=>x.id!==event.id);rtWrite('schedule',RT.schedule);rtClose();rtCalendar()},'rt-small'))}
function rtHome(){if(!currentUser)return;const today=localDate(),events=RT.schedule[today]||[],streak=RTCore.streak(RT.schedule,workoutHistory,today),active=savedRoutines.find(r=>r.id===RT.active);const themeCard=$('#themeCard');$('#homeSection').innerHTML=`<div class="rt-grid"><div class="card"><span class="rt-badge">${rtEscape(RTCore.level(RT.profile.months||0,RT.profile.frequency||0))}</span><h2 style="margin-top:16px">Hoy es ${new Date().toLocaleDateString('es-AR',{weekday:'long'})}</h2><div id="rtToday"></div><p class="rt-muted">Rutina activa: ${rtEscape(active?.name||'Sin seleccionar')}</p><button id="rtHomePlan" class="primary">Planificar mi semana</button></div><div class="card"><h2>${streak>=3?'🔥 ':''}${streak} días programados cumplidos</h2><p class="rt-muted">Los descansos no cortan la racha. Cumplí tu programa sin agregar sesiones para mantenerla.</p><div id="rtProgressHint"></div><button id="rtHomeAchievements" class="primary">Ver logros</button></div></div>`;$('#homeSection').append(themeCard);if(!events.length)$('#rtToday').textContent='Hoy no hay entrenamientos programados. Podés descansar o revisar tu calendario.';for(const e of events){const r=savedRoutines.find(x=>x.id===e.routineId),d=r&&daysOf(r)[e.dayIndex];if(!d)continue;$('#rtToday').append(rtButton(d.name,()=>{openRoutine(r,e.dayIndex);showTab('train')},'primary'))}$('#rtHomePlan').onclick=()=>showTab('calendar');$('#rtHomeAchievements').onclick=()=>{rtProfile(false);$('#rtProfileAchievements').open=true};const recent=active?workoutHistory.filter(h=>h.routineId===active.id):[];if(recent.length>=6&&recent.every(h=>h.programSignature===JSON.stringify(RTCore.routine(active)))&&new Date(recent[0].finishedAt)-new Date(recent.at(-1).finishedAt)>=28*86400000){$('#rtProgressHint').innerHTML='<p>Hace varias semanas que repetís este programa. Revisá cómo te sentís y si la técnica sigue siendo cómoda. Podés mantenerlo o consultar ajustes de repeticiones, series o carga; no hace falta aumentar todo.</p>';$('#rtProgressHint').append(rtButton('Revisar rutina',()=>openRoutineEditor(active),'primary'))} }
/* Chronometer uses timestamps so laps and screen suspension do not drift. */
function rtWatchMs(){return RT.watch.elapsed+(RT.watch.start?Math.max(0,Date.now()-RT.watch.start):0)}
function rtWatchFormat(ms){const n=Math.floor(ms/10);return String(Math.floor(n/360000)).padStart(2,'0')+':'+String(Math.floor(n/6000)%60).padStart(2,'0')+':'+String(Math.floor(n/100)%60).padStart(2,'0')+'.'+String(n%100).padStart(2,'0')}
function rtWatchSave(){rtWrite('watch',RT.watch)}
function rtWatchFullscreen(on){RT.watchFull=!!on;const s=$('#watchSection');s.classList.toggle('rt-watch-fullscreen',RT.watchFull);const b=$('#rtWatchFullscreen');if(b)b.textContent=RT.watchFull?'✕ Salir':'⛶ Pantalla completa';if(RT.watchFull&&RT.watch.start)requestWakeLock()}
function rtWatchView(){const section=$('#watchSection');section.innerHTML='<div class="card rt-watch-card"><div class="rt-calendar-header"><h2>Cronómetro y vueltas</h2><button id="rtWatchFullscreen" class="fullscreenBtn" type="button"></button></div><label class="rt-watch-sport">Deporte<select id="rtWatchSport"></select></label><div id="rtWatchTime" class="rt-clock">00:00:00.00</div><div class="controls rt-watch-controls"><button id="rtWatchPrevious" type="button">← Vueltas</button><button id="rtWatchPlay" class="primary" type="button"></button><button id="rtWatchLap" type="button">Marcar vuelta →</button></div><button id="rtWatchFinish" class="primary rt-watch-finish" type="button">Finalizar y guardar</button><button id="rtWatchReset" class="rt-watch-reset" type="button">Reiniciar cronómetro</button><p class="rt-muted">Marcá vueltas sin detener el reloj. El tiempo se conserva al bloquear la pantalla.</p><div id="rtWatchLaps"></div><h3>Sesiones guardadas</h3><div id="rtWatchHistory"></div></div>';rtWatchFullscreen(!!RT.watchFull);$('#rtWatchFullscreen').onclick=()=>rtWatchFullscreen(!RT.watchFull);$('#rtWatchSport').innerHTML=SPORTS.map(s=>'<option>'+rtEscape(s)+'</option>').join('');$('#rtWatchSport').value=RT.watch.sport||RT.profile.sport||'Running';$('#rtWatchSport').onchange=()=>{RT.watch.sport=$('#rtWatchSport').value;rtWatchSave()};$('#rtWatchPrevious').onclick=()=>$('#rtWatchLaps').scrollIntoView({behavior:'smooth',block:'center'});$('#rtWatchPlay').onclick=()=>{if(RT.watch.start){RT.watch.elapsed=rtWatchMs();RT.watch.start=null;releaseWakeLock()}else{RT.watch.start=Date.now();requestWakeLock()}rtWatchSave();rtWatchPaint()};$('#rtWatchLap').onclick=()=>{if(!RT.watch.start)return rtToast('Iniciá el cronómetro para marcar una vuelta.');const elapsed=rtWatchMs(),last=RT.watch.laps.at(-1)?.elapsed||0;RT.watch.laps.push({elapsed,split:elapsed-last});rtWatchSave();rtWatchLaps()};$('#rtWatchReset').onclick=()=>{if(confirm('¿Reiniciar el cronómetro y borrar estas vueltas?')){RT.watch={elapsed:0,start:null,laps:[]};rtWatchSave();rtWatchView();releaseWakeLock()}};$('#rtWatchFinish').onclick=()=>{const elapsed=rtWatchMs();if(!elapsed)return;const sessions=rtRead('watchHistory',[]),entry={id:crypto.randomUUID(),sport:$('#rtWatchSport').value,elapsed,laps:RT.watch.laps,finishedAt:new Date().toISOString()};sessions.unshift(entry);rtWrite('watchHistory',sessions.slice(0,200));RT.watch={elapsed:0,start:null,laps:[]};rtWatchSave();releaseWakeLock();rtWatchView();rtToast('Sesión guardada · '+entry.laps.length+' vueltas',true)};rtWatchLaps();rtWatchPaint();for(const h of rtRead('watchHistory',[])){const el=document.createElement('div');el.className='rt-lap';el.textContent=new Date(h.finishedAt).toLocaleDateString('es-AR')+' · '+h.sport+' · '+rtWatchFormat(h.elapsed)+' · '+h.laps.length+' vueltas';$('#rtWatchHistory').append(el)}}
function rtWatchPaint(){if($('#rtWatchTime')){$('#rtWatchTime').textContent=rtWatchFormat(rtWatchMs());$('#rtWatchPlay').textContent=RT.watch.start?'Pausar':'Iniciar / continuar'}}
function rtWatchLaps(){const box=$('#rtWatchLaps');if(!box)return;box.innerHTML='';RT.watch.laps.forEach((l,i)=>{const row=document.createElement('div');row.className='rt-lap';row.textContent='Vuelta '+(i+1)+' · '+rtWatchFormat(l.split)+' · Total '+rtWatchFormat(l.elapsed);box.prepend(row)})}
setInterval(()=>{if(currentUser&&!$('#watchSection').classList.contains('hidden'))rtWatchPaint()},50);
/* Exercise authoring and execution. */
$('#exerciseSubmit').insertAdjacentHTML('beforebegin','<fieldset class="rt-fieldset"><legend>Opciones del ejercicio</legend><label class="rt-check"><input type="checkbox" id="rtFailure">Registrar repeticiones al fallo</label><p class="rt-muted">Es una opción de registro, no una obligación de llegar al fallo. Podés terminar la serie antes y anotar las repeticiones realizadas.</p><label class="rt-check"><input type="checkbox" id="rtUnilateral">Unilateral: derecha y luego izquierda</label><label>Superserie<select id="rtSuperset"><option value="">Sin superserie</option><option>A</option><option>B</option><option>C</option><option>D</option></select></label><p class="rt-muted">Colocá juntos los ejercicios con la misma letra: se ejecutan antes del descanso.</p><label>Dropset — kg × reps, separados por coma<input id="rtDrops" placeholder="Ej: 30x10, 20x8" maxlength="160"></label><p class="rt-muted">Las etapas se hacen sin descanso entre ellas. Dejalo vacío para una serie normal.</p></fieldset>');
const oldReset=resetExerciseForm;resetExerciseForm=function(){oldReset();$('#rtFailure').checked=false;$('#rtUnilateral').checked=false;$('#rtSuperset').value='';$('#rtDrops').value=''};
const oldEdit=editExercise;editExercise=function(i){oldEdit(i);const x=exercises[i];$('#rtFailure').checked=!!x.failure;$('#rtUnilateral').checked=!!x.unilateral;$('#rtSuperset').value=x.superset||'';$('#rtDrops').value=(x.drops||[]).map(d=>d.kg+'x'+d.reps).join(', ')};
$('#form').onsubmit=e=>{e.preventDefault();try{const drops=$('#rtDrops').value.trim()?$('#rtDrops').value.split(',').map(s=>{const m=s.trim().match(/^(\d+(?:\.\d+)?)\s*[x×]\s*(\d+)$/i);if(!m||Number(m[1])>1000||Number(m[2])<1||Number(m[2])>1000)throw Error('Usá kg x repeticiones, por ejemplo: 30x10, 20x8');return {kg:Number(m[1]),reps:Number(m[2])}}):[];if(drops.length>6)throw Error('Máximo 6 etapas por dropset.');const x=RTCore.exercise({name:$('#name').value,mode:$('#rtFailure').checked?'reps':$('#mode').value,amount:$('#amount').value,sets:$('#sets').value,rest:$('#rest').value,failure:$('#rtFailure').checked,unilateral:$('#rtUnilateral').checked,superset:$('#rtSuperset').value,drops});if(editingExerciseIndex===null)exercises.push(x);else exercises[editingExerciseIndex]=x;saveCurrentDay();resetExerciseForm();renderExercises();buildPlan()}catch(err){message($('#err'),err.message,true)}};
const oldRenderExercises=renderExercises;renderExercises=function(){oldRenderExercises();$$('#list .exercise').forEach((row,i)=>{const x=exercises[i];row.draggable=true;row.classList.add('rt-drag');const detail=document.createElement('small');detail.className='rt-muted';detail.textContent=[x.failure?'Reps realizadas':'',x.unilateral?'Derecha → izquierda':'',x.superset?'Superserie '+x.superset:'',x.drops?.length?x.drops.length+' etapas de dropset':''].filter(Boolean).join(' · ');row.firstChild.append(detail);row.lastChild.append(rtButton(RT.favorites.exercises.includes(x.name)?'★':'☆',()=>{rtFavorite('exercises',x.name);renderExercises()},'rt-small'),rtButton('↑',()=>rtMoveExercise(i,i-1),'rt-small'),rtButton('↓',()=>rtMoveExercise(i,i+1),'rt-small'));row.ondragstart=e=>e.dataTransfer.setData('text/plain','exercise:'+i);row.ondragover=e=>e.preventDefault();row.ondrop=e=>{e.preventDefault();const text=e.dataTransfer.getData('text/plain');if(/^exercise:\d+$/.test(text))rtMoveExercise(Number(text.split(':')[1]),i)}})};
function rtMoveExercise(from,to){if(to<0||to>=exercises.length||from===to)return;const [x]=exercises.splice(from,1);exercises.splice(to,0,x);resetExerciseForm();saveCurrentDay();renderExercises();buildPlan()}
buildPlan=function(){stop();plan=RTCore.build(exercises,document.querySelector('input[name=order]:checked').value);idx=-1;idle()};
const oldOpenRoutine=openRoutine;openRoutine=function(r,day=0){stop(false);clearWorkoutState();setLogs={};workoutStartedAt=null;workoutRecorded=false;RT.sessionRoutine=r.id;RT.sessionDay=day;oldOpenRoutine(r,day)};
$('#loadPanel').insertAdjacentHTML('afterend','<div id="rtWorkExtras" class="hidden"><label class="rt-check"><input id="rtLiveFailure" type="checkbox">Registrar repeticiones realizadas</label><label id="rtActualLabel" class="hidden">¿Cuántas hiciste?<input id="rtActualReps" type="number" min="0" max="1000" step="1" placeholder="Repeticiones de esta serie"></label></div><div id="rtRestExtras" class="rt-row hidden"><button id="rtRest10" class="rt-small">+10 s</button><button id="rtRest20" class="rt-small">+20 s</button><button id="rtRest60" class="rt-small">+1 min</button></div>');
for(const n of [10,20,60])$('#rtRest'+n).onclick=()=>{if(plan[idx]?.type!=='rest')return;remaining+=n;total+=n;update();saveWorkoutState()};
$('#rtLiveFailure').onchange=()=>{const p=plan[idx];if(p?.type!=='work')return;captureCurrentSet();p.failure=$('#rtLiveFailure').checked;if(p.failure){p.mode='reps';stop(false)}renderCurrentStep(false);saveWorkoutState()};$('#rtActualReps').oninput=()=>{captureCurrentSet();saveWorkoutState()};
captureCurrentSet=function(){const p=plan[idx];if(!p||p.type!=='work')return;const raw=$('#exerciseLoad').value,actual=$('#rtActualReps').value;setLogs[idx]={name:p.name,exerciseId:p.exerciseId,side:p.side||'',dropIndex:p.dropIndex??null,set:Number(p.set)||1,reps:p.mode==='reps'?(p.failure?(actual===''?null:Math.max(0,Number(actual)||0)):Number(p.amount)||0):0,kg:raw===''?0:Math.max(0,rtKg(raw)||0),mode:p.mode,amount:Number(p.amount)||0,failure:!!p.failure,completed:!!setLogs[idx]?.completed}};
renderCurrentStep=function(auto=false){const p=plan[idx];if(!p)return;const work=p.type==='work';$('#trainRoutineName').textContent=($('#routineName').value||'Rutina')+(trainingDayName?' · '+trainingDayName:'');$('#phase').textContent=work?'EJERCICIO':'DESCANSO';$('#exercise').textContent=p.name+(p.side?' · '+p.side:'')+(p.dropIndex!=null?' · Etapa '+(p.dropIndex+1):'');$('#round').textContent='Serie '+(p.set||p.round||1);$('#step').textContent=(idx+1)+' / '+plan.length;$('#next').textContent=plan[idx+1]?.name||'Fin';$('#complete').classList.toggle('hidden',!(work&&p.mode==='reps'));$('#loadPanel').classList.toggle('hidden',!work);$('#rtWorkExtras').classList.toggle('hidden',!work);$('#rtRestExtras').classList.toggle('hidden',work);if(work){$('#exerciseLoad').value=setLogs[idx]?.kg!==undefined?rtMass(setLogs[idx].kg):p.plannedKg!==undefined?rtMass(p.plannedKg):suggestedLoad(p.name)!==''?rtMass(suggestedLoad(p.name)):'';$('#rtLiveFailure').checked=!!p.failure;$('#rtActualLabel').classList.toggle('hidden',!p.failure);$('#rtActualReps').value=setLogs[idx]?.reps??''}$('#sub').textContent=work?'Serie '+(p.set||1)+' de '+p.sets:'Recuperación';rtUnitLabels();update();if(work&&p.mode==='reps'){$('#timer').textContent=p.failure?'REPS':p.amount;$('#play').textContent='—'}else if(auto)countdown();else $('#play').textContent='Continuar';if(auto)rtSpeak(work?p.name+(p.side?', lado '+p.side:''):'Descanso. Próximo ejercicio: '+(plan.slice(idx+1).find(x=>x.type==='work')?.name||'fin'));updateMediaSession()};
function rtSpeak(text){if(!RT.prefs.voice||!('speechSynthesis'in window))return;const u=new SpeechSynthesisUtterance(text);u.lang='es-AR';u.rate=1;window.speechSynthesis.cancel();window.speechSynthesis.speak(u)}
const oldPrep=prep;prep=function(){rtSpeak('Preparate. '+(plan[0]?.name||''));oldPrep()};
const oldLoadStep=loadStep;loadStep=function(i){const p=plan[idx];if(i>idx&&p?.type==='work'){if(p.failure&&($('#rtActualReps').value===''||!Number.isInteger(Number($('#rtActualReps').value))||Number($('#rtActualReps').value)<0||Number($('#rtActualReps').value)>1000)){stop(false);$('#rtActualReps').focus();return rtToast('Anotá cuántas repeticiones hiciste; podés poner 0.')}captureCurrentSet();setLogs[idx].completed=true}oldLoadStep(i);if(idx>=plan.length){$('#rtWorkExtras').classList.add('hidden');$('#rtRestExtras').classList.add('hidden');$('#timer').classList.add('rt-gold','rt-celebrate');rtSpeak('Entrenamiento completado')}else $('#timer').classList.remove('rt-gold','rt-celebrate')};
const oldIdle=idle;idle=function(){oldIdle();$('#rtWorkExtras').classList.add('hidden');$('#rtRestExtras').classList.add('hidden')};
const oldSaveState=saveWorkoutState;saveWorkoutState=function(){oldSaveState();if(currentUser&&idx>=0&&idx<plan.length)rtWrite('workoutContext',{routineId:RT.sessionRoutine,dayIndex:RT.sessionDay})};
const oldRestore=restoreWorkout;restoreWorkout=function(){const c=rtRead('workoutContext',{});RT.sessionRoutine=c.routineId||null;RT.sessionDay=c.dayIndex||0;return oldRestore()};
recordWorkout=function(){if(!currentUser||workoutRecorded||!workoutStartedAt)return;workoutRecorded=true;const logs=Object.values(setLogs).filter(x=>x?.completed),past=rtRead('records',{}),records=[];for(const h of workoutHistory)for(const l of h.setLogs||[]){const k=l.name+'|'+(l.side||'')+'|'+l.mode;const old=past[k]||{kg:0,reps:0};if(l.kg>old.kg)past[k]={kg:l.kg,reps:l.reps||0};else if(l.kg===old.kg)past[k]={kg:old.kg,reps:Math.max(old.reps,l.reps||0)}}for(const l of logs){const key=l.name+'|'+(l.side||'')+'|'+l.mode,previous=past[key];if(previous&&l.kg>previous.kg)records.push(l.name+': '+rtMassText(l.kg));past[key]=!previous||l.kg>previous.kg?{kg:l.kg,reps:l.reps||0}:l.kg===previous.kg?{kg:l.kg,reps:Math.max(previous.reps,l.reps||0)}:previous;if(previous&&l.kg===previous.kg&&(l.reps||0)>previous.reps)records.push(l.name+': '+l.reps+' reps')}rtWrite('records',past);const entry={id:crypto.randomUUID(),name:$('#routineName').value||'Rutina',routineId:RT.sessionRoutine,dayIndex:RT.sessionDay,dayName:trainingDayName,programSignature:RT.sessionRoutine&&savedRoutines.find(r=>r.id===RT.sessionRoutine)?JSON.stringify(RTCore.routine(savedRoutines.find(r=>r.id===RT.sessionRoutine))):null,localDay:localDate(),finishedAt:new Date().toISOString(),durationSec:Math.max(1,Math.round((Date.now()-workoutStartedAt)/1000)),exerciseCount:new Set(logs.map(x=>x.exerciseId??x.name)).size,totalSets:new Set(logs.map(x=>(x.exerciseId??x.name)+':'+x.set)).size,totalReps:logs.reduce((n,x)=>n+(x.reps||0),0),totalVolume:logs.filter(x=>x.mode==='reps').reduce((n,x)=>n+x.kg*(x.reps||0),0),setLogs:logs,records};loadWorkoutHistory();workoutHistory.unshift(entry);localStorage.setItem(historyKey(),JSON.stringify(workoutHistory));renderWorkoutHistory();rtToast(records.length?'Nuevo récord · '+records.slice(0,3).join(' · '):'¡Entrenamiento completado! Sesión guardada.',true)};
const oldHistoryRender=renderWorkoutHistory;renderWorkoutHistory=function(){oldHistoryRender();$$('#historyList .historyItem').forEach((el,i)=>{const h=workoutHistory[i];const volume=el.querySelectorAll('.historyStat b')[4];if(volume)volume.textContent=rtMassText(h.totalVolume||0);if(h.records?.length){const p=document.createElement('p');p.className='rt-gold';p.textContent='✦ '+h.records.join(' · ');el.append(p)}const details=document.createElement('details'),summary=document.createElement('summary');summary.textContent='Ver series y cargas';details.append(summary);for(const l of h.setLogs||[]){const p=document.createElement('p');p.className='rt-muted';p.textContent=l.name+(l.side?' · '+l.side:'')+' · Serie '+l.set+(l.dropIndex!=null?' · Etapa '+(l.dropIndex+1):'')+' · '+(l.mode==='reps'?(l.reps??'—')+' reps':l.amount+' s')+' · '+rtMassText(l.kg||0);details.append(p)}el.append(details)})};
function rtAchievements(){const sessions=workoutHistory.length,days=new Set(workoutHistory.map(h=>h.localDay||rtDate(new Date(h.finishedAt)))).size,volume=workoutHistory.reduce((n,h)=>n+(h.totalVolume||0),0),streak=RTCore.streak(RT.schedule,workoutHistory,localDate());const weeks={};Object.entries(RT.schedule).forEach(([date,events])=>{if(date>=localDate()||!events.length)return;const d=new Date(date+'T12:00:00');d.setDate(d.getDate()-(d.getDay()+6)%7);(weeks[rtDate(d)]??=[]).push([date,events])});const perfect=Object.entries(weeks).filter(([week,list])=>{const end=new Date(week+'T12:00:00');end.setDate(end.getDate()+6);return rtDate(end)<localDate()&&list.every(([date,events])=>events.every(e=>workoutHistory.some(h=>h.localDay===date&&h.routineId===e.routineId&&h.dayIndex===e.dayIndex))) }).length;const goals=[['Primer entrenamiento',sessions,1],['10 rutinas completadas',sessions,10],['30 días de entrenamiento',days,30],['Volumen registrado: 1.000 kg',volume,1000],['Una semana planificada cumplida',perfect,1],['4 semanas planificadas cumplidas',perfect,4],['Racha de 3 días programados',streak,3]];$('#achievementsSection').innerHTML='<div class="card"><h2>Logros y récords</h2><p class="rt-muted">Son registros de tu constancia, no objetivos para agregar carga o saltarte descansos. Datos de este dispositivo.</p><div class="rt-grid">'+goals.map(([name,n,target])=>`<div class="rt-fieldset"><strong class="${n>=target?'rt-gold':''}">${n>=target?'✦ ':''}${name}</strong><p>${Math.min(target,Math.floor(n))} / ${target}</p><progress class="rt-progress" max="${target}" value="${Math.min(n,target)}"></progress></div>`).join('')+'</div><h3>Mejores cargas registradas</h3><div id="rtRecords"></div></div>';for(const [key,value] of Object.entries(rtRead('records',{}))){const p=document.createElement('p');p.textContent=key.split('|').filter(Boolean).slice(0,2).join(' · ')+' · '+rtMassText(value.kg);$('#rtRecords').append(p)}}
function rtCatalog(){$('#catalogSection').innerHTML='<div class="card rt-pending"><h2>Explorar</h2><p>SECCIÓN EN PROCESO, PRONTO ESTARÁ DISPONIBLE</p></div>'}
async function rtAdmin(){const s=$('#adminSection');s.innerHTML='<div class="card"><h2>Administración</h2><p id="rtAdminStatus">Comprobando permisos…</p><div id="rtAdminTools"></div></div>';if(!navigator.onLine){$('#rtAdminStatus').textContent='Conectate a internet para administrar la app.';return}try{const {data,error}=await db.rpc('rt_is_admin');if(error||data!==true){$('#rtAdminStatus').textContent='El panel está preparado. Falta activar los permisos y la tabla de configuración en Supabase con la migración del repositorio. No se conceden permisos desde el navegador.';return}$('#rtAdminStatus').textContent='Administrador verificado';const result=await db.from('rt_app_config').select('value').eq('id','public').maybeSingle();if(result.error)throw result.error;const config=result.data?.value||{};$('#rtAdminTools').innerHTML='<form id="rtAdminForm"><label>Anuncio de inicio<input id="rtAdminNotice" maxlength="250"></label><label>Diseño global<select id="rtAdminSeason"><option value="auto">Según fecha</option><option value="none">Sin decoración</option><option value="christmas">Navidad</option><option value="newyear">Año nuevo</option><option value="kings">Reyes</option></select></label><button class="primary">Publicar configuración</button></form>';$('#rtAdminNotice').value=config.notice||'';$('#rtAdminSeason').value=config.season||'auto';$('#rtAdminForm').onsubmit=async e=>{e.preventDefault();const {error}=await db.from('rt_app_config').upsert({id:'public',value:{notice:$('#rtAdminNotice').value,season:$('#rtAdminSeason').value}});rtToast(error?'No se pudo guardar: '+error.message:'Configuración publicada')}}catch(e){$('#rtAdminStatus').textContent='No se pudo cargar el panel: '+e.message}}
async function rtPublicConfig(){try{const {data,error}=await db.from('rt_app_config').select('value').eq('id','public').maybeSingle();if(error||!data)return;if(data.value.notice){let p=$('#rtNotice');if(!p){p=document.createElement('p');p.id='rtNotice';$('.header').after(p)}p.textContent=data.value.notice}if((RT.prefs.season||'auto')==='auto'&&data.value.season&&data.value.season!=='auto')document.documentElement.dataset.season=data.value.season}catch{}}
/* Unit preferences change presentation; stored measurements remain kg and cm. */
historyProgressText=function(index){const now=bestLoads(workoutHistory[index]);for(const [name,kg] of Object.entries(now)){for(let i=index+1;i<workoutHistory.length;i++){const old=bestLoads(workoutHistory[i])[name];if(old){if(kg>old)return '+'+rtMassText(kg-old)+' en '+name+' desde el registro anterior';break}}}return ''};
const oldPhysicalRender=renderPhysical;renderPhysical=function(){oldPhysicalRender();$$('#physicalRecords .record').forEach((el,i)=>{const r=[...physicalRecords].reverse()[i];el.querySelector('small').textContent=rtMassText(r.weight)+' · '+rtHeight(r.height).toLocaleString('es-AR',{maximumFractionDigits:2})+' '+(RT.prefs.height||'cm')});const last=physicalRecords.at(-1),prev=physicalRecords.at(-2);if(last&&prev){$('#weightChange').textContent=signed(rtMass(last.weight-prev.weight),RT.prefs.mass||'kg');$('#heightChange').textContent=signed(rtHeight(last.height-prev.height),RT.prefs.height||'cm')}rtUnitLabels()};
const oldSavePhysical=savePhysical;savePhysical=function(){const w=$('#physicalWeight').value,h=$('#physicalHeight').value;$('#physicalWeight').value=rtKg(w);$('#physicalHeight').value=Number(h)*(RT.prefs.height==='m'?100:RT.prefs.height==='in'?2.54:1);oldSavePhysical();$('#physicalWeight').value=w;$('#physicalHeight').value=h};
$('#infoOverlay .infoSteps').insertAdjacentHTML('beforeend','<div class="infoStep"><b>7</b><span>Tocá el ícono de persona para abrir <strong>Mi perfil</strong>, cambiar preferencias y ver tus logros. Los colores están en Inicio.</span></div><div class="infoStep"><b>8</b><span>En <strong>Mis rutinas</strong> creá, editá, buscá e importá. En el calendario, tocá una fecha para planificar o un entrenamiento para moverlo.</span></div><div class="infoStep"><b>9</b><span>En <strong>Cronómetro</strong>, iniciá, marcá vueltas sin detener el tiempo y usá pantalla completa. Durante una rutina también podés ajustar descansos.</span></div><div class="infoStep"><b>10</b><span>Abrí la app con internet para descargarla y guardar tus rutinas antes de usarla sin conexión. Los cambios de rutinas se sincronizan al volver; historial, calendario y favoritos quedan en este dispositivo.</span></div>');
$('#updatesOverlay .updateList').innerHTML=['Calendario más simple: tocá un día para planificar.','Cronómetro con controles ordenados como en entrenamiento.','Cronómetro y vueltas en pantalla completa.','Perfil en el ícono de persona con tus logros.','Los colores ahora están en Inicio.','Crear y editar rutinas desde Mis rutinas.','Tus rutinas y el buscador reunidos en una sola sección.','Explorar queda preparado para las rutinas que llegarán después.'].map(x=>'<li>'+x+'</li>').join('');
showUpdatesOnce=function(){if(!currentUser||!RT.profile.completed||updatesOpened||localStorage.getItem(UPDATES_VERSION)==='seen')return;setTimeout(()=>{if($('#rtDialogOverlay').classList.contains('hidden'))showUpdates(true)},300)};
rtConnection();

const rtOldNew=newRoutine;newRoutine=function(){RT.sessionRoutine=null;RT.sessionDay=0;setLogs={};workoutStartedAt=null;workoutRecorded=false;rtOldNew()};$('#newRoutine').onclick=newRoutine;

const rtPreviousSaveRoutine=$('#saveRoutine').onclick;$('#saveRoutine').onclick=async e=>{await rtPreviousSaveRoutine(e);if($('#saveMsg').textContent==='Rutina guardada ✓'){rtCloseEditor();$('#rtMineHeading').scrollIntoView({behavior:'smooth',block:'start'})}};
const rtPreviousOpenRoutineEditor=openRoutineEditor;openRoutineEditor=function(r){rtPreviousOpenRoutineEditor(r);rtOpenEditor()};
const rtNewRoutineInMine=newRoutine;newRoutine=function(){rtNewRoutineInMine();rtOpenEditor()};$('#newRoutine').onclick=newRoutine;
