/* Pure data functions shared by the application and regression tests. */
(function(root){
const num=(v,lo,hi,fallback)=>Number.isFinite(Number(v))?Math.min(hi,Math.max(lo,Number(v))):fallback;
function level(months,frequency){return months>=36&&frequency>=4?'Pro':months>=12&&frequency>=2?'Avanzado':'Principiante'}
function exercise(x){if(!x||typeof x.name!=='string'||!x.name.trim())throw Error('Ejercicio sin nombre');return {name:x.name.trim().slice(0,80),mode:x.mode==='time'?'time':'reps',amount:num(x.amount,1,3600,12),sets:Math.round(num(x.sets,1,30,3)),rest:num(x.rest,0,1800,30),failure:!!x.failure,unilateral:!!x.unilateral,superset:String(x.superset||'').slice(0,12),drops:Array.isArray(x.drops)?x.drops.slice(0,6).map(d=>({kg:num(d.kg,0,1000,0),reps:Math.round(num(d.reps,1,1000,10))})):[]}}
function routine(r){if(!r||typeof r.name!=='string'||!r.name.trim())throw Error('Falta el nombre de la rutina');let days=r.settings?.days||[{name:'Día 1',exercises:r.exercises}];if(!Array.isArray(days)||!days.length||days.length>31)throw Error('Cantidad de días inválida');days=days.map((d,i)=>{if(!Array.isArray(d.exercises)||d.exercises.length>100)throw Error('Lista de ejercicios inválida');return {name:String(d.name||'Día '+(i+1)).slice(0,80),exercises:d.exercises.map(exercise)}});if(!days.some(d=>d.exercises.length))throw Error('La rutina está vacía');return {name:r.name.slice(0,80),exercises:days[0].exercises,settings:{days,prep:r.settings?.prep===5?5:3,beep:[0,3,5].includes(r.settings?.beep)?r.settings.beep:3,order:r.settings?.order==='straight'?'straight':'circuit',sport:String(r.settings?.sport||'General').slice(0,60)}}}
function build(xs,order){let out=[];const groups=[];xs.forEach((x,i)=>{const last=groups.at(-1);if(x.superset&&last?.[0].x.superset===x.superset)last.push({x,i});else groups.push([{x,i}])});function emit(group,s){const valid=group.filter(({x})=>s<=x.sets);valid.forEach(({x,i})=>{for(const side of x.unilateral?['Derecha','Izquierda']:['']){const drops=x.drops?.length?x.drops:[null];drops.forEach((drop,di)=>out.push({...x,type:'work',exerciseId:i,name:x.name,side,dropIndex:drop?di:null,plannedKg:drop?.kg,mode:drop?'reps':x.mode,amount:drop?.reps??x.amount,set:s,round:s}))}});if(valid.length){const rest=valid.at(-1).x.rest;if(rest>0)out.push({type:'rest',name:'Descanso',amount:rest,round:s})}}
if(order==='straight')groups.forEach(g=>{for(let s=1;s<=Math.max(...g.map(a=>a.x.sets));s++)emit(g,s)});else for(let s=1;s<=Math.max(0,...xs.map(x=>x.sets));s++)groups.forEach(g=>emit(g,s));if(out.at(-1)?.type==='rest')out.pop();return out}
function duplicateName(name,names){const base=name.replace(/ \(\d+\)$/,'');let n=2;while(names.includes(base+' ('+n+')'))n++;return base+' ('+n+')'}
function scheduledEvents(schedule,recurring,date){const events=[...(schedule[date]||[])];const weekday=new Date(date+'T12:00:00').getDay();for(const item of recurring||[]){if(item.start>date||item.end&&date>item.end||new Date(item.start+'T12:00:00').getDay()!==weekday||item.excluded?.includes(date))continue;if(!events.some(e=>e.routineId===item.routineId&&e.dayIndex===item.dayIndex))events.push({...item,id:item.id+':'+date,recurringId:item.id})}return events}
function expandedSchedule(schedule,recurring,end){const out={...schedule};for(const item of recurring||[]){if(item.start>end)continue;const day=new Date(item.start+'T12:00:00');const last=item.end&&item.end<end?item.end:end;while(day<=new Date(last+'T12:00:00')){const key=day.getFullYear()+'-'+String(day.getMonth()+1).padStart(2,'0')+'-'+String(day.getDate()).padStart(2,'0');out[key]=scheduledEvents(schedule,recurring,key);day.setDate(day.getDate()+7)}}return out}
function streak(schedule,completed,today){let count=0;const dates=Object.keys(schedule).filter(d=>d<=today&&schedule[d].length).sort().reverse();for(const day of dates){const ok=schedule[day].every(p=>completed.some(h=>h.localDay===day&&h.routineId===p.routineId&&h.dayIndex===p.dayIndex));if(day===today&&!ok)continue;if(!ok)break;count++}return count}
root.RTCore={level,exercise,routine,build,duplicateName,scheduledEvents,expandedSchedule,streak};if(typeof module!=='undefined')module.exports=root.RTCore;
})(typeof window==='undefined'?globalThis:window);
