const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {JSDOM}=require('jsdom');
const root=__dirname+'/../';
function app(){const html=fs.readFileSync(root+'index.html','utf8');const dom=new JSDOM(html,{url:'https://routinetimer.github.io',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;w.structuredClone=structuredClone;w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLMediaElement.prototype.play=()=>Promise.resolve();w.HTMLMediaElement.prototype.pause=()=>{};w.HTMLCanvasElement.prototype.getContext=()=>null;w.requestAnimationFrame=()=>0;w.confirm=()=>true;w.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session:null}}),onAuthStateChange:()=>{},signOut:async()=>{},updateUser:async()=>({error:null})},from:()=>{const b={select:()=>b,eq:()=>b,order:()=>Promise.resolve({data:[],error:null}),upsert:()=>Promise.resolve({error:null}),delete:()=>b,maybeSingle:()=>Promise.resolve({data:null,error:null})};return b},rpc:async()=>({data:false})})};for(const script of ['features-core.js'])w.eval(fs.readFileSync(root+script,'utf8'));const core=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)][0][1];vm.runInContext(core,dom.getInternalVMContext());vm.runInContext(fs.readFileSync(root+'features.js','utf8'),dom.getInternalVMContext());return {w,dom,run:s=>vm.runInContext(s,dom.getInternalVMContext())}}
test('login, signup fields, authenticated tabs and settings render',async()=>{const {w,dom,run}=app();try{run('authView()');assert.equal(w.document.querySelector('#appTabs').classList.contains('hidden'),true);await run("sign('signup')");assert.ok(w.document.querySelector('#sufrequency'));assert.equal(w.document.querySelector('#suage').required,false);run("currentUser={id:'test-a',email:'test@example.invalid',user_metadata:{training_profile:{completed:true,months:12,frequency:3}}};authView()");for(const tab of ['home','calendar','watch','achievements','catalog'])run(`showTab('${tab}')`);run('rtProfile(false)');assert.ok(w.document.querySelector('#pfvoice'));assert.match(w.document.querySelector('#accountChip').textContent,/Avanzado/);await new Promise(resolve=>setImmediate(resolve))}finally{dom.window.close()}});
test('unilateral dropset, reps log and loads remain correct in lbs',()=>{const {w,dom,run}=app();try{run("currentUser={id:'test',email:'x'};RT.prefs={mass:'lbs'};exercises=[RTCore.exercise({name:'A',mode:'reps',amount:10,sets:1,rest:30,unilateral:true,drops:[{kg:20,reps:10},{kg:10,reps:8}]})];buildPlan();workoutStartedAt=Date.now();loadStep(0)");assert.equal(w.document.querySelector('#exerciseLoad').value,'44.092452436');run('loadStep(1)');assert.equal(run('setLogs[0].kg'),20);assert.equal(run('setLogs[0].completed'),true);assert.equal(run('plan[idx].dropIndex'),1);run('loadStep(2);loadStep(3);loadStep(4)');assert.equal(run('workoutHistory[0].totalVolume'),560);assert.equal(run('workoutHistory[0].totalSets'),1);assert.equal(run('workoutHistory[0].setLogs.length'),4)}finally{dom.window.close()}});
test('failure requires actual reps and stores entered zero',()=>{const {w,dom,run}=app();try{run("currentUser={id:'test',email:'x'};exercises=[RTCore.exercise({name:'A',mode:'reps',amount:10,sets:1,rest:0,failure:true})];buildPlan();workoutStartedAt=Date.now();loadStep(0);loadStep(1)");assert.equal(run('idx'),0);w.document.querySelector('#rtActualReps').value='0';run('loadStep(1)');assert.equal(run('workoutHistory[0].totalReps'),0)}finally{dom.window.close()}});
test('shared code preserves multiple days without account information',()=>{const {dom,run}=app();try{run("var example={name:'Árbol 💪',user_id:'private',settings:{days:[{name:'Lunes',exercises:[RTCore.exercise({name:'A'})]},{name:'Martes',exercises:[RTCore.exercise({name:'B'})]}]}}; var decoded=rtDecode(rtEncode(example))");assert.equal(run('decoded.name'),'Árbol 💪');assert.equal(run('decoded.settings.days.length'),2);assert.equal(run('decoded.user_id'),undefined)}finally{dom.window.close()}});
test('offline queue and routines stay isolated per account',async()=>{const {w,dom,run}=app();try{Object.defineProperty(w.navigator,'onLine',{value:false,configurable:true});run("currentUser={id:'one',email:'one'}");await run("rtSaveRoutine({name:'Offline',exercises:[RTCore.exercise({name:'A'})]})");assert.equal(run("rtRead('queue',[]).length"),1);run("currentUser={id:'two',email:'two'}");await run('loadRoutines()');assert.equal(run('savedRoutines.length'),0);run("currentUser={id:'one',email:'one'}");await run('loadRoutines()');assert.equal(run('savedRoutines[0].name'),'Offline')}finally{dom.window.close()}});
test('stopwatch laps do not stop the clock and paused state survives view changes',()=>{const {w,dom,run}=app();try{run("currentUser={id:'clock'};rtWatchView();RT.watch={elapsed:10000,start:Date.now()-2000,laps:[]}");w.document.querySelector('#rtWatchLap').click();assert.equal(run('RT.watch.laps.length'),1);assert.ok(run('RT.watch.start'));assert.ok(run('RT.watch.laps[0].elapsed')>=12000);w.document.querySelector('#rtWatchPlay').click();assert.equal(run('RT.watch.start'),null);assert.ok(run("rtRead('watch',{}).elapsed")>=12000)}finally{dom.window.close()}});
test('extra rest adds time without changing training step',()=>{const {w,dom,run}=app();try{run("currentUser={id:'rest'};exercises=[RTCore.exercise({name:'A',sets:2,rest:30})];buildPlan();loadStep(0);loadStep(1);stop(false)");w.document.querySelector('#rtRest20').click();assert.equal(run('idx'),1);assert.equal(run('remaining'),50);assert.equal(run('total'),50)}finally{dom.window.close()}});
test('restoring a session preserves load, actual reps and identity',()=>{const {w,dom,run}=app();try{run("currentUser={id:'restore'};RT.sessionRoutine='r1';RT.sessionDay=2;exercises=[RTCore.exercise({name:'A',failure:true})];buildPlan();loadStep(0)");w.document.querySelector('#exerciseLoad').value='25';w.document.querySelector('#rtActualReps').value='9';run("saveWorkoutState();setLogs={};idx=-1;restoreWorkout()");assert.equal(w.document.querySelector('#exerciseLoad').value,'25');assert.equal(w.document.querySelector('#rtActualReps').value,'9');assert.equal(run('RT.sessionRoutine'),'r1');assert.equal(run('RT.sessionDay'),2)}finally{dom.window.close()}});
